[build]
	publish = "dist/"

[[redirects]]
	from = "/works/*"
	to = "/works/:name.html"
	status = 200

[[redirects]]
	from = "/works"
	to = "/works.html"
	status = 200

[[redirects]]
	from = "/disneyplus"
	to = "/disneyplus-client"
	status = 200