[build]
	publish = "dist/"

[[redirects]]
	from = "/works/disneyplus"
	to = "/works/disneyplus-client"

[[redirects]]
	from = "/works/*"
	to = "/works/:name.html"
	status = 200

[[redirects]]
	from = "/works"
	to = "/works.html"
	status = 200